main: fabaindaiz.modulator.Modulator
name: Modulator
version: 0.5.3
description: Load plugin modules in Server
api-version: 1.14
load: POSTWORLD
author: fabaindaiz
website: uchilecraft.cl
softdepend: [ Vault ]
loadbefore: [ Vault ]
commands:
  modulator:
    description: Main command
    permission: modulator.command
permissions:
  modulator.adm:
    default: false
  modulator.mod:
    default: op
  modulator.don:
    default: op
  modulator.use:
    default: true