version: 0.5.5
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# Lottery settings
lottery:
  # Enable and disable lottery module
  enable: true
  # Use Vault economy Api
  usevault: true
  # Make lottery ticket invalid
  # Do not activate if usevault is true
  novalid: false
  # Price to buy lottery ticket
  pricelottery: 1000
  # Money prize to lottery winner
  collect: 500000