version: 0.4.0
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# Bettor settings
bettor:
  # Enable and disable bettor module
  enable: true
  # dynamic betting rewards
  dynamic: true
  # manual activation required
  onlyevents: true