version: 0.5.1
# Modulator plugin configuration file

# Bettor settings
bettor:
  # Enable and disable bettor module
  enable: true
  # dynamic betting rewards
  dynamic: true
  # manual activation required
  onlyevents: true