version: 0.4.0
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# Democracy settings
democracy:
  # Enable and disable democracy module
  enable: true
  # Make questions anonymously
  noname: false