version: 0.4.0
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# Modulator settings
modulator:
  # modulator command alias (default: md)
  alias: md

# Bettor settings
bettor:
  # Enable and disable bettor module
  enable: true
  # dynamic betting rewards
  dynamic: true
  # manual activation required
  onlyevents: true

# Democracy settings
democracy:
  # Enable and disable democracy module
  enable: true
  # Make questions anonymously
  noname: false

# Hunter settings
hunter:
  # Enable and disable hunter module
  enable: true
  # Hunted player dont lose inventory
  keepinventory: true

# ItemChat settings
itemchat:
  # Enable and disable itemchat module
  enable: true
  # All item can be shown in chat
  norestriction: true
  # Use Vault economy Api
  usevault: true
  # Price to set item owner
  priceowner: 500

# Lottery settings
lottery:
  # Enable and disable lottery module
  enable: true
  # Use Vault economy Api
  usevault: true
  # Make lottery ticket invalid
  # Do not activate if usevault is true
  novalid: false
  # Price to buy lottery ticket
  pricelottery: 1000
  # Money prize to lottery winner
  collect: 500000

# Zanakik settings
zanakik:
  # Enable and disable zanakik module
  enable: true
  # Only console can zkik a player
  noplayerzkik: true
  # All players are zanakikeable
  ignorebypass: false