version: 0.5.5
# Modulator plugin configuration file

# Updater settings
updater:
  # Enable and disable updater module
  enable: true
  # Server name for update
  server: none
  # Api key for connection
  apikey: none